AWSTemplateFormatVersion: 2010-09-09
Description: Template for RDS

Parameters: 
  VpcId:
    Type: AWS::EC2::VPC::Id
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: must contain only alphanumeric characters.
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

# Mappings: 

# Conditions: 

Resources: 
#############################################
# DB INSTANCE
#############################################
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      DBInstanceClass: db.t3.micro
      AvailabilityZone: ap-southeast-1a
      DBInstanceIdentifier: mydatabase
      DBName: !Ref DBName
      DBSubnetGroupName: DBSubnetGroup
      Engine: mysql
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      # MultiAZ: true|false
      Port: 3306
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId

  rdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: DBSubnetGroup
      DBSubnetGroupDescription: subnet group
      SubnetIds: !Split [',', !Join [',', !Ref Subnets]]
#############################################
# SECURITY GROUP
#############################################
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: security group for DB
      GroupDescription: allows ingress from instance on port 3306 for MySQL
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
